name: CI
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: ['5.0.100-preview.7.20366.6']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup .NET Core ${{ matrix.dotnet_version }}
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: ${{ matrix.dotnet_version }}

      - name: Build Spadecs on ${{ matrix.os }}
        working-directory: ./Spadecs
        run: |
          dotnet build --configuration Release
